export const navigationName={
    ListCourses:"Courses",
    CourseStudy:"Course Study",
    Home:"Home",
    First:"First",
    Login:"Login",
    Register:"Register",
    ForgetPassword:"Forget Password",
    Authentication:"Authentication",
    AfterLogin:"After Login",
    Browse:"Browse",
    Search:"Search",
    Download:"Download",
    ListDownload:"Downloads",
    Authors:"Authors",
    Paths:"Paths",
    Setting:"Setting",
    Account:"Account",
    Theme:"Theme",
    RelatedPathsAndCourses:'Related Paths And Courses',
    Categories:"Categories",
    AuthorDetail:"Author Detail",
    LessonDetail:"Lesson Detail",
    MyCourses:"My Courses",
    ListRecommendCourse:"Recommend Courses",
    ListCoursesBookmark:"List Courses Bookmark",
    VideoDownload:"Video Download",
    ListDownload:"List Download",
    UpdateProfile:"Update Profile",
    Language:"Language",
}