export const languageEng={
    Home:"Home",
    Login:"Login",
    Register:"Register",
    Email:"Email",
    ForgetPassword:"Forget Password",
    SendNewPassword:"Send new password",
    LoginSuccess:"Login successfully",
    LoginFailed:"Login failed",
    RegisterSuccess:"Register successfully",
    RegisterFailed:"Email or phone is existed",
    RegisterFailedRepassword:"You must re-type password correctly",
    RegisterRequest:"Please fill all information",
    Password:"Password",
    Username:"Username",
    RetypePassword:"Re-type password",
    Phone:"Phone",
    Name:"Name",
    Update:"Update",
    Light:"Light",
    Dark:"Dark",
    Theme:"Theme",
    Setting:"Setting",
    Account:"Account",
    SignOut:"Sign out",
    UpdateProfile:"Update profile",
    ChooseAvatar:"Click to choose your new avatar",
    Unbookmark:"Unbookmark",
    Bookmark:"Bookmark",
    Buy:"Buy",
    Bought:"Bought",
    Download:"Download",
    Size:"Size",
    Progress:"Progress",
    Comment:"Comment",
    FormalityPoint:"Formality Point",
    ContentPoint:"Content Point",
    PresentationPoint:"Presentation Point",
    Rating:"Rating",
    Contents:"Contents",
    SeeAll:"See all",
    Authors:"Authors",
    Author:"Author",
    Categories:"Categories",
    Recommend:"Recommend",
    New:"New",
    Trending:"Trending",
    Paid:"Paid",
    Downloaded:"Downloaded",
    Search:"Search",
    All:"All",
    English:"English",
    Vietnam:"Việt Nam",
    Language:"Language",
    EmptySearchMessage:"Can't find course with that keyword",
    RecentSearch:"Recent search",
    Show:"Show",
    Hide:"Hide",
    Delete:"Delete",
    Course:"Course",
    CourseStudy:"Detail course",
    CopyToClipboard:"Copy to Clipboard",
    CopyToClipboardSuccess:"Copy to Clipboard successfully",
    
}
