export const languageViet={
    Home:"Trang chủ",
    Login:"Đăng nhập",
    Register:"Đăng ký",
    Email:"Email",
    ForgetPassword:"Quên mật khẩu",
    SendNewPassword:"Gửi mật khẩu mới",
    LoginSuccess:"Đăng nhập thành công",
    LoginFailed:"Đăng nhập thất bại",
    RegisterSuccess:"Đăng ký thành công",
    RegisterFailed:"Email hay số điện thoại đã tồn tại",
    RegisterFailedRepassword:"Bạn phải nhập lại mật khẩu chính xác",
    RegisterRequest:"Hãy nhập đủ thông tin",

    Password:"Mật khẩu",
    Username:"Tài khoản",
    RetypePassword:"Nhập lại mật khẩu",
    Phone:"Số điện thoại",
    Name:"Họ tên",
    Update:"Cập nhât",
    Light:"Sáng",
    Dark:"Tối",
    Theme:"Theme",
    Setting:"Cài đặt",
    Account:"Tài khoản",
    SignOut:"Đăng xuất",
    UpdateProfile:"Cập nhật hồ sơ",
    ChooseAvatar:"Nhấn để chọn avatar mới",
    Unbookmark:"Unbookmark",
    Bookmark:"Bookmark",
    Buy:"Mua",
    Bought:"Đã mua",
    Download:"Download",
    Size:"Size",
    Progress:"Tiến độ",
    Comment:"Bình luận",
    FormalityPoint:"Điểm hình thức",
    ContentPoint:"Điểm nội dung",
    PresentationPoint:"Điểm trình bày",
    Rating:"Đánh giá",
    Contents:"Nội dung",
    SeeAll:"Xem thêm",
    Authors:"Tác giả",
    Author:"Tác giả",
    Categories:"Thể loại",
    Recommend:"Đề cử",
    New:"Mới",
    Trending:"Xu hướng",
    Paid:"Đã mua",
    Downloaded:"Đã tải",
    Search:"Tìm",
    All:"Tất cả",
    English:"English",
    Vietnam:"Việt Nam",
    Language:"Ngôn ngữ",
    EmptySearchMessage:"Không tìm thấy khóa học với từ khóa này",
    RecentSearch:"Tìm gần đây",
    Show:"Hiện",
    Hide:"Ẩn",
    Delete:"Xóa",
    Course:"Khóa học",
    CourseStudy:"Chi tiết khóa học",
    CopyToClipboard:"Copy to Clipboard",
    CopyToClipboardSuccess:"Copy to Clipboard thành công",

}
